backend:
  name: git-gateway
  branch: main # or your default branch

media_folder: "static/images/uploads" # Media files will be stored in this folder
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/english/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

