backend:
  name: git-gateway
  branch: main # or your default branch

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/english/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Title", name: "meta_title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]}

  - name: "pages"
    label: "Pages"
    folder: "content/english/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Title", name: "meta_title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "elements"
    label: "Elements"
    files:
      - file: "content/english/pages/elements.md"
        label: "Elements Page"
        name: "elements"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta Title", name: "meta_title", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Draft", name: "draft", widget: "boolean", default: false}
          - {label: "Body", name: "body", widget: "markdown"}

widgets:
  - name: "shortcodes"
    label: "Shortcodes"
    widget: "object"
    fields:
      - name: "toc"
        label: "Table of Contents"
        widget: "object"
        fields:
          - {label: "Enable", name: "enable", widget: "boolean", default: true}
      - name: "notice"
        label: "Notice"
        widget: "object"
        fields:
          - {label: "Type", name: "type", widget: "select", options: ["note", "tip", "info", "warning"]}
          - {label: "Content", name: "content", widget: "text"}
      - name: "tabs"
        label: "Tabs"
        widget: "list"
        fields:
          - {label: "Tab Title", name: "title", widget: "string"}
          - {label: "Tab Content", name: "content", widget: "markdown"}
      - name: "accordion"
        label: "Accordion"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
      - name: "image"
        label: "Image"
        widget: "object"
        fields:
          - {label: "Source", name: "src", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - name: "gallery"
        label: "Gallery"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - name: "slider"
        label: "Slider"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - name: "youtube"
        label: "YouTube Video"
        widget: "string"
      - name: "video"
        label: "Custom Video"
        widget: "object"
        fields:
          - {label: "Source", name: "src", widget: "string"}
          - {label: "Autoplay", name: "autoplay", widget: "boolean", default: false}
          - {label: "Loop", name: "loop", widget: "boolean", default: false}
          - {label: "Muted", name: "muted", widget: "boolean", default: false}
          - {label: "Controls", name: "controls", widget: "boolean", default: true}

